apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /data
      name: redispv

  volumes:
  - name: redispv
    hostPath:  
      path: /data
      type: Directory 
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx 
    image: nginx:mainline-alpine3.22-perl
    command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /data
      name: nginxpv

  volumes:
  - name: nginxpv
    hostPath:  
      path: /data
      type: Directory 